[package]
name = "flp_abyss_viewer"
version = "0.1.0"
edition = "2021"
authors = ["Hakukano <hakukano@flp-web.org>"]
description = "Media viewer that sees all"
repository = "https://github.com/Hakukano/FLP-Abyss-Viewer"
documentation = "https://docs.rs/flp_abyss_viewer"
homepage = "https://flp-abyss-viewer.rs/"
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20"
image = "0.24"
once_cell = "1.17"
rand = "0.8"
rfd = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3"
