name: CI

on:
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo deny
        run: cargo install cargo-deny
      - run: make audit
  lint:
    needs:
      - audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gstreamer-linux
      - uses: dtolnay/rust-toolchain@stable
      - run: make lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gstreamer-linux
      - uses: dtolnay/rust-toolchain@stable
      - run: make test
